import {
  addRoleToUser,
  addVolunteerToNgoByEmail,
  approveNgo,
  approveVolunteer,
  assignVolunteerToNgo,
  createNgoAccount,
  createUserQuery,
  getApprovedVolunteersByNgo,
  getNgoById,
  getNgoVolunteers,
  getPendingNgoApprovals,
  getPendingVolunteerApprovals,
  getUserByEmail,
  getUserById,
  getVolunteerNgoId,
  getVolunteerRecordByUser,
  listUserRoles,
  loginNgoByCredentials,
  loginUserByCredentials,
  rejectNgo,
  rejectVolunteer,
  setUserSelectedRole,
  updateNgoProfile,
  updateUserProfile,
} from "@/lib/db/queries/user";
import { AppRole } from "@/lib/types";

export const authApi = {
  createUser: createUserQuery,
  getUserById,
  getUserByEmail,
  loginUser: loginUserByCredentials,
  loginNgo: loginNgoByCredentials,
  createNgo: createNgoAccount,
  listUserRoles,
  setUserRole: (userId: string, role: AppRole) => setUserSelectedRole(userId, role),
  addRoleToUser: (userId: string, role: AppRole) => addRoleToUser(userId, role),
  updateUserProfile,
  getNgoById,
  updateNgoProfile,
  assignVolunteerNgo: assignVolunteerToNgo,
  addVolunteerToNgoByEmail,
  getNgoVolunteers,
  getVolunteerNgoId,
  getVolunteerRecordByUser,
  getPendingVolunteerApprovals,
  approveVolunteer,
  rejectVolunteer,
  getApprovedVolunteersByNgo,
  getPendingNgoApprovals,
  approveNgo,
  rejectNgo,
};
