import {
  acceptNgoRequest,
  acceptVolunteerPickup,
  confirmDonationCompleted,
  createDonation,
  createNgoRequest,
  deleteDonation,
  getAllDonationsForAdmin,
  getAvailableDonations,
  getDonationById,
  getDonationHistoryForExport,
  getDonationRequestsForDonor,
  getDonationSuccessStats,
  getFavoriteNgos,
  getNgoAcceptedDonations,
  getNgoCompletedDonations,
  getUserDonations,
  getVolunteerAssignedDonations,
  getVolunteerOpenPickups,
  isFavoriteNgo,
  listNgos,
  listUsers,
  listVolunteers,
  markDonationDeliveredToNgo,
  markDonationPicked,
  rejectNgoRequest,
  toggleFavoriteNgo,
  updateDonationDetails,
  updateDonationStatus,
} from "@/lib/db/queries/donation";
import { DonationStatus } from "@/lib/types";

export const donationApi = {
  create: createDonation,
  detail: getDonationById,
  delete: deleteDonation,
  listForDonor: getUserDonations,
  listAvailable: getAvailableDonations,
  listNgoAccepted: getNgoAcceptedDonations,
  listNgoCompleted: getNgoCompletedDonations,
  listVolunteerAssigned: getVolunteerAssignedDonations,
  listVolunteerOpenPickups: getVolunteerOpenPickups,
  listRequestsForDonor: getDonationRequestsForDonor,
  requestDonation: createNgoRequest,
  acceptNgoRequest,
  rejectNgoRequest,
  acceptVolunteerPickup,
  markPicked: markDonationPicked,
  markDeliveredToNgo: markDonationDeliveredToNgo,
  markCompleted: confirmDonationCompleted,
  updateDetails: updateDonationDetails,
  updateStatus: (id: string, status: DonationStatus) => updateDonationStatus(id, status),
  listAllForAdmin: getAllDonationsForAdmin,
  listUsers,
  listNgos,
  listVolunteers,
  getDonationSuccessStats,
  getFavoriteNgos,
  toggleFavoriteNgo,
  isFavoriteNgo,
  getDonationHistoryForExport,
};
