import {
  acceptNgoRequest,
  acceptVolunteerPickup,
  confirmDonationCompleted,
  createDonation,
  createNgoRequest,
  deleteDonation,
  getAllApprovedNgos,
  getAllApprovedNgosWithCompletedCounts,
  getAllDonationsForAdmin,
  getAvailableDonations,
  getDonationById,
  getDonationHistoryForExport,
  getDonationRequestsForDonor,
  getDonationSuccessStats,
  getDonorRecognitionBadge,
  getFavoriteDonors,
  getFavoriteNgos,
  getNgoAcceptedDonations,
  getNgoCompletedDonations,
  getNgoPendingRequestIds,
  getNgoProfilePublic,
  getUserDonations,
  getVolunteerAssignedDonations,
  getVolunteerOpenPickups,
  incrementDonationCount,
  isFavoriteDonor,
  isFavoriteNgo,
  listNgos,
  listUsers,
  listVolunteers,
  markDonationAsReady,
  markDonationDeliveredToNgo,
  markDonationPicked,
  markDonorHandover,
  markVolunteerPickup,
  rejectNgoRequest,
  toggleFavoriteDonor,
  toggleFavoriteNgo,
  updateDonationDetails,
  updateDonationStatus,
  updateDonorVerification,
} from "@/lib/db/queries/donation";
import { DonationStatus } from "@/lib/types";

export const donationApi = {
  create: createDonation,
  detail: getDonationById,
  delete: deleteDonation,
  listForDonor: getUserDonations,
  listAvailable: getAvailableDonations,
  listNgoAccepted: getNgoAcceptedDonations,
  listNgoCompleted: getNgoCompletedDonations,
  listVolunteerAssigned: getVolunteerAssignedDonations,
  listVolunteerOpenPickups: getVolunteerOpenPickups,
  listRequestsForDonor: getDonationRequestsForDonor,
  requestDonation: createNgoRequest,
  acceptNgoRequest,
  rejectNgoRequest,
  acceptVolunteerPickup,
  markAsReady: markDonationAsReady,
  markPicked: markDonationPicked,
  markDonorHandover,
  markVolunteerPickup,
  markDeliveredToNgo: markDonationDeliveredToNgo,
  markCompleted: confirmDonationCompleted,
  updateDetails: updateDonationDetails,
  updateStatus: (id: string, status: DonationStatus) => updateDonationStatus(id, status),
  listAllForAdmin: getAllDonationsForAdmin,
  listUsers,
  listNgos,
  listVolunteers,
  getDonationSuccessStats,
  getFavoriteNgos,
  toggleFavoriteNgo,
  isFavoriteNgo,
  getDonationHistoryForExport,
  // Feature: Favorite Donors for NGOs
  getFavoriteDonors,
  toggleFavoriteDonor,
  isFavoriteDonor,
  // Feature: NGO Public Profile
  getNgoProfilePublic,
  getAllApprovedNgos,
  getAllApprovedNgosWithCompletedCounts,
  getNgoPendingRequestIds,
  // Feature: Donor Recognition Badge
  getDonorRecognitionBadge,
  // Feature: Donor Verification
  updateDonorVerification,
  incrementDonationCount,
};
